name: CDeployment
on:
  push:
    branches:
      - 'prod'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: JayNg96/ReleasesFlow    
          
      - name: Install Libraries
        run: |
          pip install flake8 pytest pytest-cov pandas Flask Flask-MySQLdb Flask-SQLAlchemy mysql-connector-python-rf PyMySQL SQLAlchemy   

      - name: list out contents
        run: |
          ls
          
      - name: test with pytest
        run: |
          python -m pytest tests/test_* -v -cov
    
        
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'
    needs: build
    environment: PROD
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: JayNg96/ReleasesFlow
        
      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          version-file: "./package.json,./package-lock.json"
        
      - name: create release
        id: create-new-release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          
      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: ${{ steps.changelog.outputs.tag }}.zip
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./${{ steps.changelog.outputs.tag }}.zip
          asset_name: ${{ steps.changelog.outputs.tag }}.zip
          asset_content_type: application/zip
          
      - name: Create release branch
        run: |
          git branch release/${{ steps.changelog.outputs.tag }}
          git push -u origin release/${{ steps.changelog.outputs.tag }}

      - name: send zip on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Hello,
            We are excited to announce the new release of version ${{ steps.changelog.outputs.tag }} of our project.
            This release includes following changes:
            ${{ steps.changelog.outputs.clean_changelog }}
            Please take a moment to review the release notes for more details on the changes in this release.
            As always, if you have any questions or concerns, please don't hesitate to reach out to the project team.
            Best regards,
            DOT4"

          
        
